### ISSUE TITLE
usernames with special characters cause the API call to fail due to illegal characters in the URL

### ISSUE THREAD

**Issue by kmcgold** [fog/fog-softlayer#29]
Any knife-softlayer command is failing, since my SoftLayer username happens to be my e-mail, which contains the @ symbol. This causes the API call to fail when generating a URL with my SoftLayer username in the format : 

https://[username]:[apiKey]@api.[service.]softlayer.com/rest/v3/[serviceName]/[initializationParameter].[returnDatatype]

The following error is shown:
![knife-softlayer error](https://cloud.githubusercontent.com/assets/8330279/4955669/face8cee-6696-11e4-9e21-50a39a740c9f.jpg)

**Comment by fernandes** [comment]
closing due inactivity.
