### ISSUE TITLE
Excon::Errors::SocketError: hostname "XXX" does not match the server certificate (OpenSSL::SSL::SSLError)

### ISSUE THREAD

**Issue by Vic-L** [fog/fog-softlayer#35]
Hihi,
Im having issues with instantiating Softlayer's Object Storage instance. Been getting this error
```
Excon::Errors::SocketError: hostname "sng01.objectstorage.softlayer.net" does not match the server certificate (OpenSSL::SSL::SSLError)
```
I instantiate the object via this way:
```
sl_storage = Fog::Storage.new(provider: 'softlayer', softlayer_username: ENV['SL_USERNAME'], softlayer_api_key: ENV['SL_API_KEY'], softlayer_cluster: 'sng01')
```

I am thinking of disabling SSL verification to establish connection with Softlayer's object storage for now. Is there a way to do so when creating the storage object instance?

I tried the methods as mentioned here ```https://github.com/fog/fog/issues/2834```, like adding ```Fog.credentials = { path_style: true }``` to ```application.rb```, but they do not work for softlayer.

I am using ruby 2.1.2, rails 4.1.6rc1!

**Comment by cphrmky** [comment]
@Vic-L sorry for the delay, could you give a little more context here?  Are you using Paperclip as in the [example that you referenced](https://github.com/fog/fog/issues/2834)?  A little more detail on steps to reproduce please.

**Comment by Vic-L** [comment]
@cphrmky I was using these mainly these lines to render the view:
```
sl_storage = Fog::Storage.new(provider: 'softlayer', softlayer_username: ENV['SL_USERNAME'], softlayer_api_key: ENV['SL_API_KEY'], softlayer_cluster: 'sng01')
@sl_dir = sl_storage.directories.get(ENV['SL_CONTAINER'])
file = @sl_dir.files.get(filepath)
@logo_url = file.nil? ? nil : file.url(Time.now + 60)
```
I use these lines when I was uploading the image
```
image = MiniMagick::Image.open(params[:image].tempfile.path)
image.format "jpg"
image.resize "120x120"
@sl_dir.files.create(key: 'xxx.jpg', body: File.open(image.path))
```

**Comment by Vic-L** [comment]
An update from my side, I tried disabling the ssl verification in the excon gem. The view got rendered but the image file was not loaded. I checked the src of the image and found that the hostname is pointing to ```sng01.objectstorage.service.networklayer.com```. This is on my server. 

On the contrary, the hostname on my local machine, which the gem is working great, is pointing to ```sng01.objectstorage.softlayer.net```.

I believe the different hostnames is the problem, but not too sure where to look at.

**Comment by Vic-L** [comment]
@cphrmky hey I found the problem. Its a fault on my side. I have this line in ```/etc/hosts``` which is rerouting the hostname
```
10.1.129.10     sng01.objectstorage.softlayer.net
```

Really sorry about the trouble and your time! Cheers!

P.S. loving this gem <3
