### ISSUE TITLE
Support for stop/start of machines

### ISSUE THREAD

**Issue by mafraba** [fog/fog-softlayer#39]
Feature request: I see the start, stop, and reboot operations on servers are not yet implemented. I think it would be quite interesting to have them. 

Is it on the roadmap?

**Comment by cphrmky** [comment]
@mafraba happy to add this to the road map.

**Comment by mafraba** [comment]
Kind of needed it, so I'm happy to contribute.

**Comment by fernandes** [comment]
thank you very much for the PR :)

**Comment by cphrmky** [comment]
This functionality was released in v0.4.1
