### ISSUE TITLE
Large file upload example

### ISSUE THREAD

**Issue by huskercane** [fog/fog-softlayer#41]
I am trying to upload a large file. This file is bigger than 5 gig, so it needs special way to handle. 

is there a convention used by SoftLayer for these?

When I upload using swift command line, I see it create a file with name of the file and a directory with same name and ends with _segments

so if I upload x.zip, I see x.zip and x.zip_segments

I guess I am requesting a sample code. Here is mine but this made softlayer OS gui go crazy and I had to delete files using command line.

require 'fog/softlayer'
require 'pp'
require 'ruby-progressbar'
service = Fog::Storage[:softlayer]

fail 'fog_upload_2.rb <file> <container> <path>' unless ARGV.size == 3

file_name = ARGV[0]
container = ARGV[1]
dest = ARGV[2]

base_name = File.basename file_name

# this is the max we can upload in one try, otherwise we have to segment
SEGMENT_LIMIT = 5_368_709_119.0  # 5 GB -1
BUFFER_SIZE = 20 * 1_024 * 1_024 # 20 MB

# total parts
total = File.size(file_name)

progressbar = ProgressBar.create(
  title: base_name,
  :format         => '%a %bᗧ%i %p%% %t %r',
  :progress_mark  => ' ',
  :remainder_mark => '･',
  starting_at: 0,
total: total)

File.open(file_name) do |file|
  segment = 0
  until file.eof?
    segment += 1
    offset = 0

    # upload segment to cloud files
    segment_suffix = segment.to_s.rjust(10, '0')
    service.put_object(container, "#{dest}/#{base_name}/#{segment_suffix}", nil) do
      if offset <= SEGMENT_LIMIT - BUFFER_SIZE
        buf = file.read(BUFFER_SIZE)
        offset += buf.size
        progressbar.progress += BUFFER_SIZE
        # this has to be last be careful
        buf
      else
        ''
      end
    end
  end
end

# write manifest file
service.put_object_manifest(container, "#{dest}/#{base_name}", 'X-Object-Manifest' => dest)

I am using example from here
https://github.com/fog/fog/blob/master/lib/fog/rackspace/docs/storage.md#upload_large_files

I can run it with ruby large_file_upload.rb large_file.gz container path/to/file

**Comment by cphrmky** [comment]
@huskercane thanks for opening this issue, I'll take a look.

**Comment by cphrmky** [comment]
@huskercane ,

Check out the docs here:

http://ruby-doc.org/gems/docs/f/fog-softlayer-0.3.24/Fog/Storage/Softlayer/Real.html

Scroll down on that page for the methods `put_object` and `put_object_manifest`.

That's getting away from using the models a little bit and into using the requests, but it should get you what you need.

Be sure to click and expand the entries so that you can see the code examples.

**Comment by cphrmky** [comment]
I'll leave this issue open until you tell me that you're all set.

**Comment by cphrmky** [comment]
Closing this for lack of feedback.
