### ISSUE TITLE
Inconsistent username

### ISSUE THREAD

**Issue by ravinggenius** [fog/fog-softlayer#61]
**Background:**

I recently went through several days of back-and-forth with Softlayer support. My issue was resolved after discovering an inconsistency in the username. Softlayer's provides a modal on their object store page to view credentials, including URLs, username and API key. The username in the modal is much longer (something like `XXXX000000-2:SL000000`) whereas the username that `fog-softlayer` takes is only the portion after the colon (`SL000000`). Once I figured this out, everything worked.

---

It would be very helpful to check that the proper (short) username is specified, *or* to accept both (longform and short) and manually pull the short version out. If both of these options are disagreeable, please consider prompting the user to check that their username is the short version if the authorization check fails.

**Comment by mfbmina** [comment]
@ravinggenius can you tell me where did you find this long user name on softlayer panel? Then I can take a look on this issue.

**Comment by ravinggenius** [comment]
Go to Storage -> Object Storage, then pick a cluster you have setup. At the top there is an Account tab on the left (it's only one). In the tab body, click on "View Credentials".

![001](https://cloud.githubusercontent.com/assets/21517/7619754/d61c2d68-f988-11e4-86ad-020ec6f64f3d.png)

That opens a modal which has the longform username:

![002](https://cloud.githubusercontent.com/assets/21517/7619755/d620551e-f988-11e4-9f76-87be0f3e019e.png)

**Comment by cphrmky** [comment]
@ravinggenius thanks for reporting this.

@mfbmina `Fog::Storage::Softlayer` is indeed expecting the "normal" short username as explained above.  Would you mind adding this (or similar):

```ruby
@softlayer_username =~ /:/ and raise ArgumentError, "Invalid username format.  If you are using a Storage specific username, use only the part after the colon." 
```

put it right after line 105 in [`lib/fog/softlayer/storage.rb`](https://github.com/fog/fog-softlayer/blob/master/lib/fog/softlayer/storage.rb#L105) I guess
