### ISSUE TITLE
ArgumentError: Storage must be instantiated with the :temp_url_key option

### ISSUE THREAD

**Issue by ravinggenius** [fog/fog-softlayer#65]
I'm trying to generate an expiring URL following this [tutorial](http://sldn.softlayer.com/blog/matteldridge/Using-fog-softlayer-Managing-Object-Storage). Below I've presented the code I'm using to produce the error.

```ruby
options = {
  provider: 'SoftLayer',
  softlayer_username: 'secret',
  softlayer_api_key: 'so secret',
  softlayer_cluster: 'DAL05'
}
connection = Fog::Storage.new(options)
file = connection.directories.get('some key').files.first
file.url(Time.now + 300) #=> ArgumentError...
```

**Comment by mfbmina** [comment]
@ravinggenius , maybe @cphrmky can help you!

**Comment by ravinggenius** [comment]
Since the error asked for `:temp_url_key`, I added it to the `options`, but then I got another error from Fog saying that `:temp_url_key` is unknown. I went exploring the `fog-softlayer` source code a bit and found `:softlayer_temp_url_key`. I set that to some random string[1], which let me create a temporary URL. However this temporary URL didn't work; I get `401 Unauthorized: Temp URL invalid` even when the expiration is ten minutes in the future and I check it right away.

[1] I didn't find any documentation on this option, so I may be holding it wrong.

**Comment by cphrmky** [comment]
Try instantiating exactly the way the documentation for this gem shows it, with `Fog::Storage[:softlayer]` and let me know if that makes this error resolve.

**Comment by cphrmky** [comment]
@ravinggenius what I'm asking you to do is let me know what happens if you put your credentials into `~/.fog` as [shown here](https://github.com/fog/fog-softlayer/blob/master/examples/getting_started.md#usage).

Then use your same code like this: 

```ruby
file = connection.directories.get('some key').files.first
file.url(Time.now + 300) 
```

I'd like to know if that's working for you.  It should work both ways, I'd just like to narrow it down a bit, plus that would get you unblocked until a patch is applied to fix this.  Thanks.

**Comment by ravinggenius** [comment]
It doesn't work with `~/.fog`.

**Comment by cphrmky** [comment]
It's supposed to automatically find and use the `:temp_url_key` (your SL Storage account should come with one by default if I recall correctly).  In either case, you should be able to set it by passing it to options, but you need to use `:softlayer_temp_url_key` and not `:temp_url_key` as [shown here](https://github.com/fog/fog-softlayer/blob/cf0d22c1445d1490e1f9661f0736e8751c2af5d3/lib/fog/softlayer/storage.rb#L12).

**Comment by cphrmky** [comment]
@ravinggenius let me know if that gets you unstuck and I'll close this issue.

**Comment by ravinggenius** [comment]
Using `~/.fog` I get the same errors as before.

**Without `:softlayer_temp_url_key`**:

```
[1] pry(main)> require 'fog/softlayer'
=> false

[2] pry(main)> connection = Fog::Storage[:softlayer]
=> #<Fog::Storage::Softlayer::Real:70254626571020 ...>

[3] pry(main)> connection.directories.first.files.first.url(Time.now + 300)
ArgumentError: Storage must be instantiated with the :temp_url_key option
from /Users/thomas/Code/gather_digital-fog-softlayer/lib/fog/softlayer/requests/storage/get_object_https_url.rb:42:in `create_temp_url'
```

**With `:softlayer_temp_url_key`**:

```
[1] pry(main)> require 'fog/softlayer'
=> false

[2] pry(main)> connection = Fog::Storage[:softlayer]
=> #<Fog::Storage::Softlayer::Real:70272937758500 ...>

[3] pry(main)> connection.directories.first.files.first.url(Time.now + 300)
=> "https://dal05.objectstorage.softlayer.net:443/v1/AUTH_.../sample.txt?temp_url_sig=...temp_url_expires=1434398882"
```

I edited the URL before posting it here, but the full URL still returns `401 Unauthorized: Temp URL invalid`.

**Comment by jonphillips** [comment]
Is it possible to get some help or resolution here?  I am working with @ravinggenius on this, and it for a project involving IBM as a client.  Thanks!

**Comment by cphrmky** [comment]
@jonphillips / @ravinggenius ,

Try this.

```ruby
sl = Fog::Storage[:softlayer]
sl.post_set_meta_temp_url_key('someSortaSecretStuffHere')
```

See if that fixes your problem.

Please update this thread either way so I can continue to look for a solution or update the documentation depending on what happens.

Thx.

**Comment by ravinggenius** [comment]
Calling `post_set_meta_temp_url_key` did the trick! I was able to generate correct URLs using `~/.fog` in pry and in my automated test.

**Comment by cphrmky** [comment]
Thx for the update @ravinggenius, also for reporting this issue.  I've updated the docs with 500f5a1.

/cc @jonphillips

**Comment by jonphillips** [comment]
Thanks @cphrmky!
