### ISSUE TITLE
Can't launch with image_id set

### ISSUE THREAD

**Issue by psschroeter** [fog/fog-softlayer#71]
Hey guys, I did a commit to back out a change here:
https://github.com/psschroeter/fog-softlayer/commit/0742f7fe71c06050d9172ef144e5fe245df0fa94

Any chance this can be put in the main gem?

It says "# need this while os_code bug isn't fixed" -- what is the os_code bug exactly? Couldn't quite figure it out from the PRs/issues it was discussed in:
https://github.com/fog/fog-softlayer/pull/58
https://github.com/fog/fog-softlayer/issues/51

**Comment by cphrmky** [comment]
@psschroeter thanks for raising this, sorry to be so slow in response, was out on leave for a bit, I'll be in touch on resolving this
