### ISSUE TITLE
Cannot generate public URL

### ISSUE THREAD

**Issue by ravinggenius** [fog/fog-softlayer#75]
We are using paperclip with fog so our clients can pick their preferred storage provider. Paperclip integrates with fog, so when we call `model.icon(:small)` (for instance), paperclip eventually calls `Fog::Storage::Softlayer::File#public_url`, which in turn calls `Fog::Storage::Softlayer::Files#get_url`, which calls `Fog::Storage::Softlayer::Directory#public_url`, which is explicitly not implemented.

Are public (no expiration) URLs supported?

**Comment by cphrmky** [comment]
I believe they are supported by SoftLayer's object storage (which is Swift under the covers).  It sounds like we need to add support to the fog-softlayer gem at this point.

Any interest in taking that up?  I'll support the effort as needed.

**Comment by ravinggenius** [comment]
I am working on this. Is there a base URL to which I can add a key? I've been diving pretty deep into the code with pry, but I keep coming back empty-handed.
