### ISSUE TITLE
Switch to rbvmomi2

### ISSUE THREAD

**Issue by micwoj92** [fog/fog-softlayer#8]
https://github.com/fog/fog-softlayer/blob/4f8d1f3f10b2d5e58521f838395dcaa764e749d8/fog-softlayer.gemspec#L29

As latest fog-vsphere uses rbvmomi2 rather than rbvmomi I think it makes sense to switch development dependency here.

reference
https://github.com/fog/fog-vsphere/pull/281

**Comment by micwoj92** [comment]
Wasn't changed here

https://github.com/fog/fog-softlayer/blob/be82c0026ff0a0a6be49dfc18a95dfcb180277e5/fog-softlayer.gemspec#L29

**Comment by geemus** [comment]
Thanks, looks like I changed the version constraint but missed the 2 in the name change on accident. Should be fixed now.
